export const SESSION_RECOVER = 'SESSION_RECOVER';
export const SESSION_UPDATE = 'SESSION_UPDATE';
export const SESSION_DELETE = 'SESSION_DELETE';

export const APP_LOADING = 'APP_LOADING';
export const APP_LOADED = 'APP_LOADED';
export const APP_TOKEN_UPDATE = 'APP_TOKEN_UPDATE';
export const SET_OS = 'SET_OS';

export const FILES_SET_FILES_LIST = 'FILES_SET_FILES_LIST';
export const FILES_SET_FOLDER_LIST = 'FILES_SET_FOLDER_LIST';
export const FILES_ADD_CACHED_FILES = 'FILES_ADD_CACHED_FILES';

export const PLAYER_SET_RANDOM = 'PLAYER_SET_RANDOM';
export const PLAYER_SET_REPEAT = 'PLAYER_SET_REPEAT';
export const PLAYER_SET_CURRENT_SONG = 'PLAYER_SET_CURRENT_SONG';
export const PLAYER_SET_VOLUME = 'PLAYER_SET_VOLUME';
export const PLAYER_SET_SONG_LINK = 'PLAYER_SET_SONG_LINK';
export const PLAYER_SET_IS_PLAYING = 'PLAYER_SET_IS_PLAYING';

export const FAVORITES_INITIALIZE_FAVORITES = 'FAVORITES_SET_FAVORITES';
export const FAVORITES_ADD_FAVORITE = 'FAVORITES_ADD_FAVORITE';
export const FAVORITES_REMOVE_FAVORITE = 'FAVORITES_REMOVE_FAVORITE';
export const FAVORITES_SET_IS_FAVORITE_PLAYING = 'FAVORITES_TOGGLE_IS_PLAYING';

export const SETTINGS_SET_AUTO_PLAY = 'SETTINGS_SET_AUTO_PLAY';
export const SETTINGS_SET_FULL_FILENAME = 'SETTINGS_SET_FULL_FILENAME';
export const SETTINGS_SET_DARK_THEME = 'SETTINGS_SET_DARK_THEME';
export const SETTINGS_RESTORE_PREFERENCES = 'SETTINGS_RESTORE_PREFERENCES';

export const SONGS_QUEUE_SET_SONGS = 'SONGS_QUEUE_CHANGE_SONGS';
export const SONGS_QUEUE_ADD_BROKEN_LINK = 'SONGS_QUEUE_ADD_BROKEN_LINK';
export const SONGS_QUEUE_SET_SONG_INDEX = 'SONGS_QUEUE_SET_SONG_INDEX';

export const USER_SET_USER = 'USER_SET_USER';

export const SIDEBAR_CHANGE_INDEX = 'CHANGE_SIDEBAR_INDEX';
