export const SESSION_RECOVER = 'SESSION_RECOVER';
export const SESSION_UPDATE = 'SESSION_UPDATE';
export const SESSION_DELETE = 'SESSION_DELETE';

export const APP_LOADING = 'APP_LOADING';
export const APP_LOADED = 'APP_LOADED';
export const APP_TOKEN_UPDATE = 'APP_TOKEN_UPDATE';

export const FILES_SET_FILES_LIST = 'FILES_SET_FILES_LIST';
export const FILES_SET_FOLDER_LIST = 'FILES_SET_FOLDER_LIST';

export const TOGGLE_REPEAT = 'TOGGLE_REPEAT';
export const SET_CURRENT_SONG = 'SET_CURRENT_SONG';
export const SET_VOLUME = 'SET_VOLUME';
export const SET_SONG_LINK = 'SET_SONG_LINK';

export const INITIALIZE_FAVORITES = 'SET_FAVORITES';
export const ADD_FAVORITE = 'ADD_FAVORITE';
export const REMOVE_FAVORITE = 'REMOVE_FAVORITE';
export const TOGGLE_IS_FAVORITE_PLAYING = 'TOGGLE_IS_PLAYING';

export const SET_AUTO_PLAY = 'SET_AUTO_PLAY';
export const SET_FULL_FILENAME = 'SET_FULL_FILENAME';
export const SET_DARK_THEME = 'SET_DARK_THEME';
export const RESTORE_PREFERENCES = 'RESTORE_PREFERENCES';

export const CHANGE_SONGS_QUEUE = 'CHANGE_SONGS_QUEUE';
export const ADD_BROKEN_LINK = 'ADD_BROKEN_LINK';
export const SET_SONG_INDEX = 'SET_SONG_INDEX';

export const SET_USER = 'SET_USER';

export const CHANGE_SIDEBAR_INDEX = 'CHANGE_SIDEBAR_INDEX';
