export const SESSION_RECOVER = 'SESSION_RECOVER';
export const SESSION_UPDATE = 'SESSION_UPDATE';
export const SESSION_DELETE = 'SESSION_DELETE';

export const APP_LOADING = 'APP_LOADING';
export const APP_LOADED = 'APP_LOADED';
export const APP_TOKEN_UPDATE = 'APP_TOKEN_UPDATE';
export const SET_OS = 'SET_OS';

export const FILES_SET_FILES_LIST = 'FILES_SET_FILES_LIST';
export const FILES_SET_FOLDER_LIST = 'FILES_SET_FOLDER_LIST';
export const FILES_SET_IS_LOADING = 'FILES_SET_IS_LOADING';

export const PLAYER_SET_CURRENT_SONG = 'PLAYER_SET_CURRENT_SONG';
export const PLAYER_SET_IS_LOADING = ' PLAYER_SET_IS_LOADING';
export const PLAYER_SET_PLAYLIST = ' PLAYER_SET_PLAYLIST';

export const SETTINGS_SET_AUTO_PLAY = 'SETTINGS_SET_AUTO_PLAY';
export const SETTINGS_SET_FULL_FILENAME = 'SETTINGS_SET_FULL_FILENAME';
export const SETTINGS_SET_DARK_THEME = 'SETTINGS_SET_DARK_THEME';
export const SETTINGS_RESTORE_PREFERENCES = 'SETTINGS_RESTORE_PREFERENCES';
export const SETTINGS_SET_LANG = 'SETTINGS_SET_LANG';

export const USER_SET_USER = 'USER_SET_USER';
