export const INITIALIZE_FAVORITES = 'SET_FAVORITES';
export const ADD_FAVORITE = 'ADD_FAVORITE';
export const REMOVE_FAVORITE = 'REMOVE_FAVORITE';
export const TOGGLE_IS_FAVORITE_PLAYING = 'TOGGLE_IS_PLAYING';
