export const SET_AUTO_PLAY = 'SET_AUTO_PLAY';
export const SET_FULL_FILENAME = 'SET_FULL_FILENAME';
export const SET_DARK_THEME = 'SET_DARK_THEME';
export const RESTORE_PREFERENCES = 'RESTORE_PREFERENCES';
